#!/usr/bin/env python

import rospy
import os


from std_msgs.msg import Empty


def rebootCallback(x):
    rospy.loginfo("Reboot command invoked")
    os.system("shutdown -r now")


def shutdownCallback(x):
    rospy.loginfo("Shutdown command invoked")
    os.system("shutdown -h now")


try:
    rospy.init_node('leo_system')
    pose_sub = rospy.Subscriber(
        "system/shutdown", Empty, shutdownCallback)
    pose_sub = rospy.Subscriber("system/reboot", Empty, rebootCallback)
    rospy.loginfo("Leo system node started!")
except rospy.ROSInterruptException as e:
    rospy.logerr(e)

rospy.spin()
